DEFAULT_SETTINGS: dict[tuple[str, str], object] = {
    ("model", "base_directories"): [
        "./model-directories",
        r"F:\\KI\\models",
    ],
    ("model", "active_model_id"): None,
    ("model", "relevance_flags"): {},
    ("model", "prefer_gpu"): True,
    ("model", "max_loaded_models"): 1,
    ("model", "gpu_memory_limit_mb"): 11000,
    ("chat", "plugin_orchestration_enabled"): True,
    ("chat", "auto_specialist_enabled"): False,
    ("chat", "stream_response"): True,
    ("chat", "temperature"): 0.1,
    ("chat", "max_new_tokens"): 1024,
    ("chat", "top_p"): 0.95,
    ("chat", "top_k"): 6,
    ("chat", "repetition_penalty"): 1.05,
    ("chat", "do_sample"): True,
    ("chat", "seed"): 42,
    ("chat", "stop_sequences"): ["<end_of_turn>", "<eos>"],
    ("chat", "context_limit_tokens"): 8192,
    ("chat", "context_safety_margin_tokens"): 128,
    ("chat", "conversation_context_limit_map"): {},
    ("chat", "conversation_generation_profiles_map"): {},
    ("chat", "conversation_project_map"): {},
    ("knowledge", "top_k"): 6,
    ("knowledge", "min_score_ratio"): 0.5,
    ("knowledge", "min_absolute_score"): 1000,
    ("knowledge", "min_score_gap"): 400,
    ("knowledge", "hybrid_search_enabled"): True,
    ("integrations", "chatgpt_api_key"): "",
    ("integrations", "deepl_api_key"): "",
    ("integrations", "anthropic_api_key"): "",
    ("integrations", "google_ai_api_key"): "",
    ("integrations", "mistral_api_key"): "",
    ("integrations", "cohere_api_key"): "",
    ("integrations", "perplexity_api_key"): "",
    ("integrations", "groq_api_key"): "",
    ("integrations", "together_api_key"): "",
    ("integrations", "openrouter_api_key"): "",
    ("integrations", "huggingface_api_key"): "",
    ("integrations", "replicate_api_key"): "",
    ("integrations", "deepseek_api_key"): "",
    ("integrations", "xai_api_key"): "",
    ("integrations", "elevenlabs_api_key"): "",
    ("integrations", "assemblyai_api_key"): "",
    ("integrations", "tavily_api_key"): "",
    ("integrations", "serpapi_api_key"): "",
    ("integrations", "google_maps_api_key"): "",
    ("integrations", "mapbox_api_key"): "",
    ("integrations", "openweather_api_key"): "",
    ("integrations", "weatherapi_api_key"): "",
    ("integrations", "tomorrowio_api_key"): "",
    ("integrations", "newsapi_api_key"): "",
    ("integrations", "twilio_api_key"): "",
    ("integrations", "sendgrid_api_key"): "",
    ("integrations", "slack_bot_token"): "",
    ("integrations", "discord_bot_token"): "",
    ("integrations", "github_token"): "",
    ("integrations", "notion_api_key"): "",
    ("integrations", "airtable_api_key"): "",
    ("integrations", "stripe_secret_key"): "",
    ("integrations", "azure_openai_api_key"): "",
    ("integrations", "aws_bedrock_api_key"): "",
    ("integrations", "deepinfra_api_key"): "",
    ("integrations", "nvidia_nim_api_key"): "",
    ("integrations", "octoai_api_key"): "",
    ("integrations", "fireworks_api_key"): "",
    ("integrations", "github_copilot_api_key"): "",
    ("integrations", "stability_api_key"): "",
    ("integrations", "runway_api_key"): "",
    ("integrations", "pika_api_key"): "",
    ("integrations", "heygen_api_key"): "",
    ("integrations", "fal_api_key"): "",
    ("integrations", "unstructured_api_key"): "",
    ("integrations", "llamaparse_api_key"): "",
    ("integrations", "firecrawl_api_key"): "",
    ("integrations", "pinecone_api_key"): "",
    ("integrations", "weaviate_api_key"): "",
    ("integrations", "qdrant_api_key"): "",
    ("integrations", "cloudconvert_api_key"): "",
    ("integrations", "exa_api_key"): "",
    ("integrations", "brave_search_api_key"): "",
    ("integrations", "bing_search_api_key"): "",
    ("integrations", "gnews_api_key"): "",
    ("integrations", "scrapingbee_api_key"): "",
    ("integrations", "apify_api_key"): "",
    ("integrations", "alpha_vantage_api_key"): "",
    ("integrations", "yahoo_finance_api_key"): "",
    ("integrations", "openexchangerates_api_key"): "",
    ("integrations", "whatsapp_business_api_key"): "",
    ("integrations", "telegram_bot_token"): "",
    ("integrations", "microsoft_teams_api_key"): "",
    ("integrations", "calendly_api_key"): "",
    ("integrations", "virustotal_api_key"): "",
    ("integrations", "hibp_api_key"): "",
    ("integrations", "ollama_local_enabled"): True,
    ("integrations", "custom_provider_keys"): {},
    (
        "prompt",
        "system_prompt",
    ): (
        "Du bist ein hilfreicher Assistent. "
        "Antworte standardmaessig in natuerlichem, zusammenhaengendem Fliesstext auf Deutsch. "
        "Verwende keine Markdown-Formatierungen, keine Emojis, keine Aufzaehlungen oder Nummerierungen, "
        "ausser der Nutzer verlangt sie ausdruecklich. "
        "Halte die Antwort klar, praezise und gut lesbar mit kurzen Absaetzen."
    ),
    ("training", "enabled"): False,
    ("training", "default_trainer"): "peft_lora",
    ("training", "base_model"): "",
    ("training", "artifacts_directory"): "./training-artifacts",
    ("training", "datasets_directory"): "./training-datasets",
    ("training", "max_concurrent_jobs"): 1,
    ("training", "auto_start_queue"): True,
    ("training", "auto_evaluate"): True,
    ("training", "auto_register_model"): True,
    ("training", "auto_activate_model"): True,
    ("training", "continual_training"): True,
    ("training", "continual_model_id"): None,
    ("training", "project_id"): None,
    ("training", "training_cycle_id"): "default",
    ("training", "archive_on_success"): True,
    ("training", "deduplicate_jobs"): True,
    ("training", "training_preset"): "safe",
    ("training", "num_train_epochs"): 4.0,
    ("training", "learning_rate"): 0.0001,
    ("training", "per_device_train_batch_size"): 1,
    ("training", "gradient_accumulation_steps"): 4,
    ("training", "max_sequence_length"): 768,
    ("training", "lora_r"): 16,
    ("training", "lora_alpha"): 32,
    ("training", "lora_dropout"): 0.05,
    ("training", "target_modules"): ["auto"],
    ("training", "load_in_4bit"): True,
    ("training", "warmup_ratio"): 0.05,
    ("training", "weight_decay"): 0.01,
    ("training", "eval_steps"): 10,
    ("training", "save_steps"): 10,
    ("training", "logging_steps"): 1,
    ("training", "logging_first_step"): True,
    ("training", "max_steps"): 0,
    ("training", "validation_split"): 0.1,
    ("training", "load_best_model_at_end"): True,
    ("training", "metric_for_best_model"): "eval_loss",
    ("training", "greater_is_better"): False,
    ("training", "seed"): 42,
    ("system", "language"): "de",
    ("system", "theme"): "system",
    ("system", "timezone"): "Europe/Berlin",
    ("system", "log_level"): "INFO",
    ("workspace", "project_meta_map"): {},
    ("workspace", "seed_demo_data"): True,
}

SYSTEM_HARD_LIMITS: dict[tuple[str, str], object] = {
    ("chat", "max_new_tokens"): 4096,
    ("training", "max_concurrent_jobs"): 4,
}
